CREATE OR REPLACE FUNCTION public.check_and_process_expired_delivery_dispatches(
    timeout_threshold_seconds INT DEFAULT 30
)
RETURNS TABLE (
    processed_assignment_count INT
)
LANGUAGE plpgsql
SECURITY DEFINER
AS \[ DECLARE     expired_record RECORD;     next_rider_id UUID;     next_distance DOUBLE PRECISION;     counter INT := 0; BEGIN     -- 1. Loop through all pending delivery assignments that have exceeded the response window threshold parameters     FOR expired_record IN          SELECT da.id, da.order_id, da.rider_profile_id, do.pickup_latitude, do.pickup_longitude, da.rejection_count_at_assignment         FROM public.delivery_assignments da         JOIN public.delivery_orders do ON do.id = da.order_id         WHERE da.assignment_status = 'pending'           AND da.assigned_at <= NOW() - (timeout_threshold_seconds \vert{}\vert{} ' seconds')::INTERVAL     LOOP         -- 2. Mark the active expired row parameter entry status cleanly to 'expired'         UPDATE public.delivery_assignments         SET assignment_status = 'expired',             updated_at = NOW()         WHERE id = expired_record.id;          -- 3. File a standardized timeout compliance log entry metric to apply the local GHS 2.50 infraction penalty fee values         INSERT INTO public.rider_compliance_logs (             rider_profile_id,             order_id,             violation_type,             penalty_fee         ) VALUES (             expired_record.rider_profile_id,             expired_record.order_id,             'timeout_expiry',             2.50         );          -- 4. Invoke your PostGIS spatial matching matrix calculator query to locate the next closest available fleet driver unit         SELECT matched_rider_profile_id, calculated_distance_meters         INTO next_rider_id, next_distance         FROM public.match_closest_delivery_rider(             expired_record.order_id,             expired_record.pickup_latitude,             expired_record.pickup_longitude,             5000.00 -- Re-search within a fresh 5-kilometer geometric cell grid radius         );          -- 5. If a secondary close rider candidate matches, instantly insert a fresh cascading assignment row entry parameters pointer         IF next_rider_id IS NOT NULL THEN             INSERT INTO public.delivery_assignments (                 order_id,                 rider_profile_id,                 assignment_status,                 rejection_count_at_assignment             ) VALUES (                 expired_record.order_id,                 next_rider_id,                 'pending',                 expired_record.rejection_count_at_assignment + 1             );         END IF;          counter := counter + 1;     END LOOP;      processed_assignment_count := counter;     RETURN NEXT; END; \];
